/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface NoorseBox {
    /**
    * The first name
    */
    'header': string;
  }
  interface NoorseBoxAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'header'?: string;
  }

  interface NoorseNavbar {
    'navigation': string;
  }
  interface NoorseNavbarAttributes extends StencilHTMLAttributes {
    'navigation'?: string;
    'onItemSelected'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'NoorseBox': Components.NoorseBox;
    'NoorseNavbar': Components.NoorseNavbar;
  }

  interface StencilIntrinsicElements {
    'noorse-box': Components.NoorseBoxAttributes;
    'noorse-navbar': Components.NoorseNavbarAttributes;
  }


  interface HTMLNoorseBoxElement extends Components.NoorseBox, HTMLStencilElement {}
  var HTMLNoorseBoxElement: {
    prototype: HTMLNoorseBoxElement;
    new (): HTMLNoorseBoxElement;
  };

  interface HTMLNoorseNavbarElement extends Components.NoorseNavbar, HTMLStencilElement {}
  var HTMLNoorseNavbarElement: {
    prototype: HTMLNoorseNavbarElement;
    new (): HTMLNoorseNavbarElement;
  };

  interface HTMLElementTagNameMap {
    'noorse-box': HTMLNoorseBoxElement
    'noorse-navbar': HTMLNoorseNavbarElement
  }

  interface ElementTagNameMap {
    'noorse-box': HTMLNoorseBoxElement;
    'noorse-navbar': HTMLNoorseNavbarElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
