/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface NoorseBox {
    /**
    * The first name
    */
    'header': string;
  }
  interface NoorseNavbar {
    'navigation': string;
  }
}

declare global {


  interface HTMLNoorseBoxElement extends Components.NoorseBox, HTMLStencilElement {}
  var HTMLNoorseBoxElement: {
    prototype: HTMLNoorseBoxElement;
    new (): HTMLNoorseBoxElement;
  };

  interface HTMLNoorseNavbarElement extends Components.NoorseNavbar, HTMLStencilElement {}
  var HTMLNoorseNavbarElement: {
    prototype: HTMLNoorseNavbarElement;
    new (): HTMLNoorseNavbarElement;
  };
  interface HTMLElementTagNameMap {
    'noorse-box': HTMLNoorseBoxElement;
    'noorse-navbar': HTMLNoorseNavbarElement;
  }
}

declare namespace LocalJSX {
  interface NoorseBox extends JSXBase.HTMLAttributes<HTMLNoorseBoxElement> {
    /**
    * The first name
    */
    'header'?: string;
  }
  interface NoorseNavbar extends JSXBase.HTMLAttributes<HTMLNoorseNavbarElement> {
    'navigation'?: string;
    'onItemSelected'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'noorse-box': NoorseBox;
    'noorse-navbar': NoorseNavbar;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


