/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface NoorseBox {
    /**
    * The first name
    */
    'header': string;
  }
  interface NoorseBoxAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'header'?: string;
  }

  interface NoorseHeader {
    'navigation': string;
  }
  interface NoorseHeaderAttributes extends StencilHTMLAttributes {
    'navigation'?: string;
    'onItemSelected'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'NoorseBox': Components.NoorseBox;
    'NoorseHeader': Components.NoorseHeader;
  }

  interface StencilIntrinsicElements {
    'noorse-box': Components.NoorseBoxAttributes;
    'noorse-header': Components.NoorseHeaderAttributes;
  }


  interface HTMLNoorseBoxElement extends Components.NoorseBox, HTMLStencilElement {}
  var HTMLNoorseBoxElement: {
    prototype: HTMLNoorseBoxElement;
    new (): HTMLNoorseBoxElement;
  };

  interface HTMLNoorseHeaderElement extends Components.NoorseHeader, HTMLStencilElement {}
  var HTMLNoorseHeaderElement: {
    prototype: HTMLNoorseHeaderElement;
    new (): HTMLNoorseHeaderElement;
  };

  interface HTMLElementTagNameMap {
    'noorse-box': HTMLNoorseBoxElement
    'noorse-header': HTMLNoorseHeaderElement
  }

  interface ElementTagNameMap {
    'noorse-box': HTMLNoorseBoxElement;
    'noorse-header': HTMLNoorseHeaderElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
